name: ci-fullcycle-golang-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-g0@v2
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go
